### ISSUE TITLE
 SQL-监控 无数据

### ISSUE THREAD

**Issue by learninto** [MyCATApache/Mycat-Web#117]

**Comment by magichuihui** [comment]
Mycat 1.6
要设置conf/server.xml里的useSqlStat 为 1，开启实时监控

**Comment by learninto** [comment]
好的，谢谢你

**Comment by superleo-cn** [comment]
打开了，还是没有数据。 

```
 <property name="useSqlStat">1</property>  <!-- 1为开启实时统计、0为关闭 -->
```

**Comment by hehaiwangjin** [comment]
你的问题解决了吗？怎么解决的？谢谢

**Comment by learnintoning** [comment]
@hehaiwangjin 没有解决，现在不用mycat了。

**Comment by messi18** [comment]
> Mycat 1.6
要设置conf/server.xml里的useSqlStat 为 1，开启实时监控

设置完这个之后，重启mycat。然后，在mycat-web中把mycat的配置删掉，重新配一次。我这样操作了一遍，就可以了。

**Comment by cywang4** [comment]
我的也不行，useSqlStat也设置为1，web上的mysql也删了再加，还是不行

**Comment by nogolang** [comment]
谢谢了,真的是吐了,这个问题搞了我一天.谢谢,useSqlStat设置为1后,还需要重启mycat,以及重新连接mycat-web
