### ISSUE TITLE
mycat-web 监控数据为空

### ISSUE THREAD

**Issue by cjldw** [MyCATApache/Mycat-Web#119]
mycat1.6 下的conf/server.xml设置了useSqlStat为1

查看报错信息 database is locked?

查询失败,系统异常!case:
↵### Error querying database.
  Cause: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)↵
### Cause: java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)↵; uncategorized SQLException for SQL []; SQL state [null]; error code [5]; [SQLITE_BUSY]  The database file is locked (database is locked); nested exception is java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)

**Comment by chenwei97** [comment]
兄弟解决了吗，遇到和你一样的坑，搞了几天了没有头绪。

**Comment by cjldw** [comment]
问题好像是sqlite文件锁定了, 你暂停服务, 然后复制sqlite数据库文件, 然后把原来的删除掉, 再把复制的文件重命名到原来那个文件, 在启动服务, 我这样做可以了, 但没过多久, 又锁了, 最后把sqllite换成了mysql
