### ISSUE TITLE
README.MD ‘体验 Mycat’部分没有看懂

### ISSUE THREAD

**Issue by kkxue** [MyCATApache/Mycat-Web#63]
Hello!
README.MD中，
////////////////////////
体验 Mycat

启动Navicat Premium
连接Mycat，IP:8066 test/test
连接TESTDB
测试
      select * from t_user;
////////////////////////
我用navicat连接之后，有db1,db2,db3，没有TESTDB.

**Comment by sohudo** [comment]
你连接的是mysql 所以没看到TESTDB

**Comment by kkxue** [comment]
后面看《mycat权威指南》明白了
